FROM python:3.12-slim

# Install curl for the health check and mlflow
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir mlflow

WORKDIR /app

# mlflow.db will live inside the named volume mounted at /app/db
EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///db/mlflow.db", \
     "--default-artifact-root", "./mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--allowed-hosts", "*"]